/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *const sp_sym_names[3] = {(&("\xff" "initialize")[1]), (&("\xff" "scale")[1]), (&("\xff" "cache")[1])};
static const char *sp_dyn_syms[SP_DYN_SYMS_MAX]; static int sp_ndyn = 0;
static const char *sp_sym_to_s(sp_sym id){if(id>=0&&id<3)return sp_sym_names[id];if(id>=3&&id<3+sp_ndyn)return sp_dyn_syms[id-3];return "";}
static sp_sym sp_sym_intern(const char *s){for(int i=0;i<3;i++)if(strcmp(sp_sym_names[i],s)==0)return (sp_sym)i;for(int i=0;i<sp_ndyn;i++)if(strcmp(sp_dyn_syms[i],s)==0)return (sp_sym)(3+i);if(sp_ndyn<SP_DYN_SYMS_MAX){sp_dyn_syms[sp_ndyn]=sp_str_dup_external(s);return (sp_sym)(3+sp_ndyn++);}return (sp_sym)0;}

static const char *sp_class_to_s(sp_Class c){if(c.name)return c.name;switch(c.cls_id){case 0:return SPL("Factory");case -100:return SPL("Integer");case -101:return SPL("Float");case -102:return SPL("String");case -103:return SPL("Symbol");case -104:return SPL("Array");case -105:return SPL("Hash");case -106:return SPL("Range");case -107:return SPL("Time");case -108:return SPL("Module");case -109:return SPL("Class");case -110:return SPL("NilClass");case -111:return SPL("TrueClass");case -112:return SPL("FalseClass");case -113:return SPL("Numeric");case -114:return SPL("Comparable");case -115:return SPL("Enumerable");case -116:return SPL("Object");case -117:return SPL("BasicObject");case -118:return SPL("Proc");case -119:return SPL("Kernel");case -120:return SPL("IO");case -121:return SPL("File");case -122:return SPL("Exception");case -123:return SPL("StandardError");case -124:return SPL("RuntimeError");case -125:return SPL("TypeError");case -126:return SPL("ArgumentError");case -127:return SPL("NameError");case -128:return SPL("NoMethodError");case -129:return SPL("StopIteration");case -130:return SPL("Math");case -131:return SPL("Complex");default:return "";} }

static const int sp_cls_is_module[1] = {0};
static int sp_class_is_module_val(sp_Class c){
  if(c.cls_id>=0&&c.cls_id<1)return sp_cls_is_module[c.cls_id];
  return(c.cls_id==-114||c.cls_id==-115||c.cls_id==-119);
}
static sp_Class sp_class_superclass(sp_Class c){
  switch(c.cls_id){
  case 0: return ((sp_Class){-116});
  default: return ((sp_Class){-116});
  }
}
static sp_Class sp_builtin_superclass(sp_Class c);
static int sp_class_is_ancestor(sp_Class anc, sp_Class desc);
static int sp_class_is_ancestor(sp_Class anc, sp_Class desc){
  sp_Class cur = desc;
  for(int _i=0;_i<41;_i++){
    if(cur.cls_id==anc.cls_id)return 1;
    if(cur.cls_id==-117)break;
    sp_Class next=cur.cls_id>=0?sp_class_superclass(cur):sp_builtin_superclass(cur);
    if(next.cls_id==cur.cls_id)break;
    cur=next;
  }
  return 0;
}
static sp_Class sp_builtin_superclass(sp_Class c){
  switch(c.cls_id){
  case -100:case -101: return ((sp_Class){-113});
  case -102:case -103:case -104:case -105:case -106:case -107:case -113: return ((sp_Class){-116});
  case -122: return ((sp_Class){-116});
  case -123:case -124: return ((sp_Class){-122});
  case -125:case -126:case -127:case -129: return ((sp_Class){-123});
  case -128: return ((sp_Class){-127});
  case -110:case -111:case -112:case -118: return ((sp_Class){-116});
  case -108: return ((sp_Class){-116});
  case -109: return ((sp_Class){-108});
  case -116: return ((sp_Class){-117});
  case -117: return ((sp_Class){-117});
  default: return ((sp_Class){-116});
  }
}
static int sp_class_lt(sp_Class a,sp_Class b){return a.cls_id!=b.cls_id&&sp_class_is_ancestor(b,a);}
static int sp_class_le(sp_Class a,sp_Class b){return sp_class_is_ancestor(b,a);}
static int sp_class_gt(sp_Class a,sp_Class b){return sp_class_lt(b,a);}
static int sp_class_ge(sp_Class a,sp_Class b){return sp_class_le(b,a);}
static sp_PolyArray *sp_class_ancestors(sp_Class c){
  sp_PolyArray *a=sp_PolyArray_new();
  sp_Class cur=c;
  for(int _i=0;_i<21;_i++){
    if(cur.cls_id<0){
      while(1){
        sp_PolyArray_push(a,sp_box_class(cur));
        if(cur.cls_id==-113) sp_PolyArray_push(a,sp_box_class(((sp_Class){-114})));
        if(cur.cls_id==-104||cur.cls_id==-105) sp_PolyArray_push(a,sp_box_class(((sp_Class){-115})));
        if(cur.cls_id==-102) sp_PolyArray_push(a,sp_box_class(((sp_Class){-114})));
        if(cur.cls_id==-116) sp_PolyArray_push(a,sp_box_class(((sp_Class){-119})));
        sp_Class bn=sp_builtin_superclass(cur);
        if(bn.cls_id==cur.cls_id)break;
        cur=bn;
      }
      break;
    }
    sp_PolyArray_push(a,sp_box_class(cur));
    switch(cur.cls_id){
    }
    sp_Class next=sp_class_superclass(cur);
    if(next.cls_id==cur.cls_id)break;
    cur=next;
  }
  return a;
}

static int sp_class_le_mod(sp_Class a,sp_Class b){
  /* a<=b: b is an ancestor of a, so b must appear in a's ancestors */
  sp_PolyArray *ancs=sp_class_ancestors(a);
  for(mrb_int _i=0;_i<sp_PolyArray_length(ancs);_i++){
    sp_RbVal v=sp_PolyArray_get(ancs,_i);
    if(v.tag==7&&(int)v.cls_id==b.cls_id)return 1;
  }
  if(b.cls_id<0)return sp_class_is_ancestor(b,a);
  return 0;
}
#undef sp_class_le
#define sp_class_le sp_class_le_mod
#undef sp_class_lt
#define sp_class_lt(a,b) ((a).cls_id!=(b).cls_id&&sp_class_le_mod(a,b))
#undef sp_class_gt
#define sp_class_gt(a,b) ((a).cls_id!=(b).cls_id&&sp_class_le_mod(b,a))
#undef sp_class_ge
#define sp_class_ge(a,b) sp_class_le_mod(b,a)
static sp_Class sp_poly_get_class(sp_RbVal v){
  switch(v.tag){
  case SP_TAG_INT: return ((sp_Class){-100});
  case SP_TAG_STR: return ((sp_Class){-102});
  case SP_TAG_FLT: return ((sp_Class){-101});
  case SP_TAG_BOOL: return v.v.b?((sp_Class){-111}):((sp_Class){-112});
  case SP_TAG_NIL: return ((sp_Class){-110});
  case SP_TAG_SYM: return ((sp_Class){-103});
  case SP_TAG_OBJ: if(v.cls_id>=0)return ((sp_Class){v.cls_id});
    if(v.cls_id>=-12)return ((sp_Class){-104});
    if(v.cls_id>=-20)return ((sp_Class){-105});
    return ((sp_Class){-116});
  default: return ((sp_Class){-116});
  }
}
static int sp_poly_is_a(sp_RbVal obj,sp_Class klass){
  return sp_class_le(sp_poly_get_class(obj),klass);
}
static const char *sp_user_exc_parent(const char *cls){
  (void)cls;
  return 0;
}
typedef struct sp_Factory_s sp_Factory;
struct sp_Factory_s {
  mrb_int cls_id;
  mrb_int iv_n;
};

static mrb_int civ_Factory_n = SP_INT_NIL;
static void sp_Factory_initialize(sp_Factory *self, mrb_int lv_n);
static sp_RbVal sp_Factory_scale(sp_Factory self, sp_RbVal lv_k);
static sp_PolyPolyHash * sp_Factory_cache(sp_Factory self);
static sp_Factory sp_Factory_new(mrb_int);

static void sp_re_init(void) {
  sp_sym_name_fn = sp_sym_to_s;
  sp_user_exc_parent_fn = sp_user_exc_parent;
}

static sp_RbVal _sp_hash_dproc_1(sp_PolyPolyHash *_self_h, sp_RbVal _key, void *_dproc_self) {
  (void)_dproc_self;
  sp_PolyPolyHash *lv_h = _self_h; (void)lv_h;
  sp_RbVal lv_k__bp23 = _key; (void)lv_k__bp23;
  sp_RbVal _t3 = lv_k__bp23;
  SP_GC_ROOT_RBVAL(_t3);
  sp_RbVal _t2 = sp_Factory_scale(self, _t3);
  sp_PolyPolyHash_set(lv_h, lv_k__bp23, _t2);
  return _t2;
}

static sp_Factory sp_Factory_new(mrb_int lv_n) {
  sp_Factory self = {0};
  self.cls_id = 0;
  self.iv_n = SP_INT_NIL;
  sp_Factory_initialize(&self, lv_n);
  return self;
}
static int sp_marshal_obj_dump(sp_mar_buf *b, int cls_id, void *p) {
  switch (cls_id) {
    default: return 0;
  }
}
static sp_RbVal sp_marshal_obj_load(const char *name, sp_RbVal iv_boxed, int *ok) {
  sp_PolyArray *iv = (sp_PolyArray *)iv_boxed.v.p;
  *ok = 1; (void)iv;
  *ok = 0; return sp_box_nil();
}
#line 2 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
static void sp_Factory_initialize(sp_Factory *self, mrb_int lv_n) {
    SP_GC_SAVE();
  self->iv_n = lv_n;
}
#line 3 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
static sp_RbVal sp_Factory_scale(sp_Factory self, sp_RbVal lv_k) {
    SP_GC_SAVE();
    SP_GC_ROOT_RBVAL(lv_k);
  return sp_poly_mul(sp_box_int(self.iv_n), lv_k);
  return sp_box_nil();
}
#line 4 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
static sp_PolyPolyHash * sp_Factory_cache(sp_Factory self) {
    SP_GC_SAVE();
    sp_PolyPolyHash * lv_h = NULL;
    SP_GC_ROOT(lv_h);
    sp_RbVal lv_k__bp23 = sp_box_nil();
    SP_GC_ROOT_RBVAL(lv_k__bp23);
  return sp_PolyPolyHash_new_dproc(_sp_hash_dproc_1, NULL);
  return NULL;
}
int main(int argc,char**argv){
    SP_GC_SAVE();
    sp_re_init();
    sp_program_name = argc > 0 ? argv[0] : "";
    sp_PolyPolyHash * lv_c = NULL;
    SP_GC_ROOT(lv_c);
    mrb_int lv_i = 0;

#line 1 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
#line 6 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
  sp_Factory  _t4 = sp_Factory_new(10LL);
  lv_c = sp_Factory_cache(_t4);
#line 7 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
  for (mrb_int _t6 = 0; _t6 < 1000LL; _t6++) {
    lv_i = _t6;
    sp_IntArray *_t7 = sp_IntArray_new();
    SP_GC_ROOT(_t7);
    sp_IntArray_push(_t7, lv_i);
    sp_IntArray_push(_t7, lv_i);
    sp_IntArray_push(_t7, lv_i);
    _t7;
  }
#line 8 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
  fputs(sp_poly_inspect(sp_PolyPolyHash_get(lv_c, sp_box_int(3LL))), stdout); putchar('\n');
#line 9 "/private/tmp/claude-501/-Users-ryanseys-dev-spinel-upstreaming/50f35961-f94e-4575-890b-f09974ee2f28/scratchpad/gc.rb"
  fputs(sp_poly_inspect(sp_PolyPolyHash_get(lv_c, sp_box_int(5LL))), stdout); putchar('\n');
  return 0;
}
