#!/usr/bin/env ruby
# gen_manifest.rb -- regenerate an expectations manifest from a full
# measurement, applying the by-design ledger.
#
# Usage: ruby tools/rubyspec/gen_manifest.rb RESULTS_TSV > expectations/X.tsv
#
# A REJECT whose diagnostic matches a BYDESIGN pattern becomes
# REJECT-BYDESIGN: a permanent, deliberate exclusion (spinel is a subset;
# see docs/limitations.md "Fundamental limits") that leaves the adjusted
# score's denominator. Everything else keeps its measured status; frontier
# REJECTs stay plain REJECT so the ranking keeps pointing at them.
#
# Keep this list conservative: by-design is a declaration that the example
# will NEVER pass, so when in doubt leave it on the frontier.

BYDESIGN = [
  /eval of a runtime string/,           # needs a runtime parser (AOT-fundamental)
  /singleton class on arbitrary object/ # per-object method tables vs direct C calls
].freeze

results = ARGV[0] or abort "usage: gen_manifest.rb RESULTS_TSV"

rows = File.readlines(results).map { |l| l.chomp.split("\t", 3) }

puts "# ruby/spec expectations manifest -- generated by gen_manifest.rb from a"
puts "# full measurement at RUBYSPEC_REV (see Makefile). One row per example:"
puts "# name<TAB>status. PASS rows are the retention gate's contract"
puts "# (make rubyspec-gate); REJECT-BYDESIGN rows are permanent exclusions"
puts "# (docs/limitations.md); the rest record the frontier. Regenerate"
puts "# deliberately, reviewing the diff, never by hand."

counts = Hash.new(0)
rows.each do |name, status, detail|
  next unless name && status
  if status == "REJECT" && detail && BYDESIGN.any? { |re| re =~ detail }
    status = "REJECT-BYDESIGN"
  end
  counts[status] += 1
  puts "#{name}\t#{status}"
end

pass = counts["PASS"]
bydesign = counts["REJECT-BYDESIGN"]
skew = counts["HARNESS-SKEW"]
total = counts.values.sum
denom = total - bydesign - skew
warn "manifest: #{pass} PASS / #{counts["FAIL"]} FAIL / #{counts["REJECT"]} REJECT " \
     "/ #{bydesign} REJECT-BYDESIGN / #{counts["ERROR"]} ERROR / #{skew} SKEW"
warn format("adjusted score: %d/%d = %.1f%% (denominator excludes by-design and skew)",
            pass, denom, 100.0 * pass / denom)
