/* Internal shared declarations for the split analyzer (was one 8.4k-line
 * file): util (helpers) / infer (type inference) / scope (registration &
 * specialization) / pass (fixpoint passes) / analyze.c (driver). */
#ifndef SPINEL_ANALYZE_INTERNAL_H
#define SPINEL_ANALYZE_INTERNAL_H
#include "analyze.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The receiver class for a node inside an instance_eval/exec block, or -1. */
int ie_class_of(Compiler *c, int node);

/* Forward declarations for FFI helpers defined later in this file. */
const char *ffi_arg_str(const NodeTable *nt, int nid);
int ffi_arg_int(const NodeTable *nt, int nid);
TyKind ffi_spec_to_ty(const char *spec);
int ffi_find_func(Compiler *c, const char *mod, const char *name);
int ffi_find_buf(Compiler *c, const char *mod, const char *name);
int ffi_find_reader(Compiler *c, const char *mod, const char *name);



/* Returns 1 if user class ci (or any ancestor in user chain) has a builtin
   exception as direct superclass (per its ClassNode superclass field). */


/* ---- operator classification ---- */


/* ---- call inference ---- */

/* Resolve a struct member from a literal key node: a SymbolNode names a
   member; an IntegerNode is a positional index. Returns the member index
   (0-based, matching ivar order) or -1. */

/* Last statement of a scope's body, or -1. */

/* The return type of a call to method `mi`. A method whose body is just a
   bare `yield` returns the block's value -- and since it inlines per call
   site, use THIS site's block value type rather than the unified return. */
/* 1 if `node` is `<&block-param>.call(...)` / .() / [] for method mi -- the
   explicit-call equivalent of `yield`, inlined the same way. */

/* Re-entrancy guard for yield_value_type: prevents infinite recursion when a
   recursive method forwards its block to itself (e.g. countdown { blk.call }). */
#define MAX_YVT_DEPTH 32
extern int g_yvt_mi[MAX_YVT_DEPTH];
extern int g_yvt_depth;

/* Temporary class override for instance_eval block body inference.
   -1 = no override; set to the receiver's class_id while inferring
   the block body so that InstanceVariableReadNode uses the right class. */
extern int an_ie_class_id;
/* Class index of the class/module body currently being analyzed (set around
   ClassNode/ModuleNode body traversal). -1 outside any class body. */
extern int g_cbody_class_id;
/* Like g_cbody_class_id, but cleared when descending into a method/block scope:
   the class index only while walking a class/module body's *direct* statements,
   where `self` is the class object. -1 inside method bodies and at top level.
   Mirrors codegen's g_class_body_id so a self/bare `class_eval` reopen is
   recognized identically by analyze and codegen. */
extern int g_cbody_direct;

/* Scan a subtree for BreakNode values and return their unified type.
   Stops at DefNode/BlockNode boundaries (inner blocks have their own break scope). */

/* Unify the value types of every `throw <tag>, <val>` inside a catch block.
   A nested inner BlockNode is still scanned because `throw` is dynamic. */

/* The value type of `yield` / a `<&block-param>.call` inside method mi: the
   block-body value type at a (any) call site of mi. Polymorphic, resolved from
   the first matching caller -- matches how the rewrite inlines per call site. */


/* 1 if `id` is a proc/lambda literal: `proc {}` / `lambda {}` (CallNode with
   no receiver and a block) or `Proc.new {}`. */

/* 1 if `id` is any proc-creating literal: a proc/lambda/Proc.new call (above)
   or a `->(){}` LambdaNode. */

/* The body return type of a proc-creating node (proc/lambda CallNode literal,
   or a LambdaNode). The last statement of the block/lambda body is the value. */

/* The body return type (`#call`'s result) of a proc-valued expression, or
   TY_UNKNOWN if not statically known. Resolves a literal directly, a local's
   recorded proc_ret, and a method call's recorded ret_proc_ret. */

/* The return type of a proc-typed expression's `.call`; poly when unknown. */

/* method(:sym) helpers (defined in analyze_util.c, shared with codegen) */
const char *method_sym_arg(Compiler *c, int node);
int is_method_obj_call(Compiler *c, int node);
int method_obj_target_mi(Compiler *c, int node);
int method_recv_node(Compiler *c, int recv);

extern int g_inc_did_clone;
extern int *g_ie_node_class;

typedef struct { const char **v; int n, cap; } ANameSet;
#define QC_MAXDEPTH 8
typedef struct { int node; char path[QC_MAXDEPTH][64]; int depth; char name[128]; } QCWrite;

/* ---- cross-part function declarations (generated by the split) ---- */
int is_builtin_class_name(const char *n);
int is_builtin_exception_name(const char *n);
int class_inherits_builtin_exception(Compiler *c, int ci);
int an_re_has_captures(const char *src);
int str_in(const char *s, const char *const *set);
int is_arith_op(const char *op);
int is_cmp_op(const char *op);
int is_eq_op(const char *op);
int is_void_call(const char *name);
int struct_member_idx(Compiler *c, ClassInfo *sc, int keynode);
int scope_body_last(Compiler *c, int mi);
int is_blk_param_call(Compiler *c, int node, int mi);
TyKind scan_break_type(Compiler *c, int id, int depth);
TyKind scan_throw_type(Compiler *c, int id, int depth);
TyKind yield_value_type(Compiler *c, int mi);
TyKind method_call_ret(Compiler *c, int mi, int call_id);
/* is_proc_constant / is_proc_literal are declared in analyze.h (codegen needs them). */
int is_proc_create(Compiler *c, int id);
TyKind proc_node_ret(Compiler *c, int create);
TyKind proc_ret_of(Compiler *c, int node);
TyKind proc_call_ret(Compiler *c, int recv);
TyKind infer_call(Compiler *c, int id);
TyKind infer_uncached(Compiler *c, int id);
void scope_add_param(Scope *s, const char *name, int defnode);
void collect_def_params(Compiler *c, int def_id, Scope *s);
char *dm_lit_str(Compiler *c, int lit);
char *dm_eval_name(Compiler *c, int node, const char *bv, int lit);
TyKind dm_lit_type(Compiler *c, int lit);
int collect_dm_each_unroll(Compiler *c, int id, int class_id);
const char *builtin_class_of_type(TyKind t);
const char *resolve_class_alias(Compiler *c, const char *cname);
void walk_scope(Compiler *c, int id, int scope_idx, int class_id);
void register_module_functions(Compiler *c);
void register_locals(Compiler *c);
int is_struct_call(Compiler *c, int val);
void register_struct_members(Compiler *c, ClassInfo *cls, int val);
void register_structs(Compiler *c);
void fix_struct_block_scopes(Compiler *c);
void register_attr_call(Compiler *c, ClassInfo *cls, int s, int singleton);
void register_attrs_body(Compiler *c, ClassInfo *cls, int body);
void register_attrs(Compiler *c);
void register_aliases_body(Compiler *c, ClassInfo *cls, int body);
void register_aliases(Compiler *c);
void register_undefs_body(Compiler *c, ClassInfo *cls, int body);
void register_undefs(Compiler *c);
int is_c_ident(const char *s);
void register_globals_consts(Compiler *c);
const char *ffi_arg_str(const NodeTable *nt, int nid);
int ffi_arg_int(const NodeTable *nt, int nid);
TyKind ffi_spec_to_ty(const char *spec);
void register_ffi_decls(Compiler *c);
int ffi_find_func(Compiler *c, const char *mod, const char *name);
int ffi_find_buf(Compiler *c, const char *mod, const char *name);
int ffi_find_reader(Compiler *c, const char *mod, const char *name);
int infer_global_const_types(Compiler *c);
int infer_multiwrite_const_types(Compiler *c);
void resolve_parents(Compiler *c);
void process_include_body(Compiler *c, int ci, int body_node);
void register_includes(Compiler *c);
void register_extends(Compiler *c);
int cmethod_has_bare_new(Compiler *c, int mi);
int cmethod_needs_specialization(Compiler *c, int mi, int ci, int def_cls, int *has_new);
void specialize_inherited_cls_new(Compiler *c);
void register_prepends(Compiler *c);
void inherit_members(Compiler *c);
int infer_inherited_ivars(Compiler *c);
int infer_cvar_types(Compiler *c);
int infer_ivar_types(Compiler *c);
/* 1 if `name` (incl '@') is an ivar pinned by an --rbs seed in class `ci`;
   the ivar inference write sites consult this to avoid widening a pinned slot. */
int class_ivar_pinned(ClassInfo *ci, const char *name);
void sp_ivwatch(const char *name, const char *where, TyKind old, TyKind nw);
void sp_narrow_memo_bump(void);
int infer_write_types(Compiler *c);
int infer_param_hash_value(Compiler *c);
int bind_call_params(Compiler *c, int call_id, int mi);
int propagate_prep_params(Compiler *c);
int infer_default_param_types(Compiler *c);
int is_string_only_method(const char *m);
int infer_params_from_ivar_hash_ops(Compiler *c);
int infer_hash_params(Compiler *c);
int infer_array_params(Compiler *c);
int infer_string_params(Compiler *c);
int infer_param_types(Compiler *c);
int infer_for_index(Compiler *c);
void infer_bigint_loop_locals(Compiler *c);
int first_yield(Compiler *c, int si);
int first_block_call_args(Compiler *c, int si);
int a_proc_params_node(Compiler *c, int create);
int infer_block_params(Compiler *c);
int desugar_value_callable_forwards(Compiler *c);
int desugar_enum_chain_to_a(Compiler *c);
int desugar_implicit_send(Compiler *c);
TyKind return_node_type(Compiler *c, int id);
int infer_return_types(Compiler *c);
void cr_collect_calls(const NodeTable *nt, int id, char ***out, int *n, int *cap);
void compute_reachable(Compiler *c);
int aname_has(ANameSet *s, const char *nm);
void aname_add(ANameSet *s, const char *nm);
int a_nested_block(const char *ty);
int a_is_local_node(const char *ty);
int a_is_write_node(const char *ty);
void a_mark_subtree(Compiler *c, int id, char *inproc);
void a_collect_used(Compiler *c, int id, ANameSet *out);
int a_proc_params_node(Compiler *c, int create);
int a_proc_body(Compiler *c, int create);
int a_block_is_lifted(Compiler *c, int id);
int a_proc_create_or_lifted(Compiler *c, int id);
void mark_proc_captures(Compiler *c);
void bigint_scan_body(const NodeTable *nt, int id, char ***names, int *n, int *cap);
void detect_bigint_loop_vars(Compiler *c);
void propagate_bigint_cascade(Compiler *c);
void mark_ie_subtree(Compiler *c, int node, int cls);
void build_ie_map(Compiler *c);
int ie_class_of(Compiler *c, int node);
int blkp_params_node(Compiler *c, int create);
int blkp_binds_param(Compiler *c, int create, const char *name);
int lv_node_is_named_ref(const char *ty);
int lv_node_is_write(const char *ty);
void blkp_rewrite_refs(Compiler *c, int node, const char *oldn, const char *newn);
void blkp_mark_subtree(const NodeTable *nt, int node, char *marks);
int blkp_needs_rename(Compiler *c, int L);
void qc_collect_writes(Compiler *c, int node, char (*path)[64], int depth, QCWrite **ws, int *n, int *cap);
int qc_read_chain(const NodeTable *nt, int node, char (*chain)[64], int *abs_anchor);
void qc_qualified_name(char *out, size_t cap, const QCWrite *w);
void qc_rewrite_reads(Compiler *c, int node, char (*mods)[64], int mdepth, QCWrite *ws, int wn);
void qualify_colliding_consts(Compiler *c);
void qc_collect_class_writes(Compiler *c, int node, char (*path)[64], int depth, QCWrite **ws, int *n, int *cap);
void qualify_colliding_classes(Compiler *c);
void rename_shadowing_block_params(Compiler *c);
void topup_forwarding_arity(Compiler *c);
/* Defined in codegen.c; the analyzer uses it to specialize/type a
   `rescue <UserExc> => e` binding (#1415). */
int class_is_exc_subclass(Compiler *c, int ci);
/* Defined in codegen_fold.c; 1 if class `k` is `anc` or a descendant of it. */
int is_descendant(Compiler *c, int k, int anc);
#endif

